version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: nest_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: todos
      JWT_SECRET: your_jwt_secret

volumes:
  postgres_data:
